{
 "title": "Gatling Prometheus Realtime",
 "tags": [
  "gatling",
  "prometheus",
  "realtime",
  "load-test"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "request",
    "label": "Request",
    "query": {
     "query": "label_values(gatling_requests_total, request)"
    }
   },
   {
    "name": "simulation",
    "label": "Simulation",
    "query": {
     "query": "label_values(gatling_requests_total, simulation)"
    }
   },
   {
    "name": "scenario",
    "label": "Scenario",
    "query": {
     "query": "label_values(gatling_requests_total, scenario)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"})",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "KO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ko\"}) or vector(0)",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "Req/s (Mean)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\"}[1m]))",
     "legendFormat": "Req/s"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_active_users{simulation=~\"$simulation\", scenario=~\"$scenario\"})",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "OK/KO",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_requests_total{status=\"ok\"})",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ko\"}) or vector(0)",
     "legendFormat": "KO"
    }
   ]
  },
  { "title": "Response Time Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Min (~P1)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "50th pct",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "75th pct",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    }
   ]
  },
  {
   "title": "95th pct",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "99th pct",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Max (~P99.9)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Response Time Ranges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response Time Ranges",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"800.0\", status=\"ok\"}) or vector(0)",
     "legendFormat": "t < 800ms"
    },
    {
     "expr": "(sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"1200.0\", status=\"ok\"}) - sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"800.0\", status=\"ok\"})) or vector(0)",
     "legendFormat": "800ms ≤ t < 1200ms"
    },
    {
     "expr": "(sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"+Inf\", status=\"ok\"}) - sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"1200.0\", status=\"ok\"})) or vector(0)",
     "legendFormat": "t ≥ 1200ms"
    },
    {
     "expr": "sum(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ko\"}) or vector(0)",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"800.0\", status=\"ok\"}) or vector(0)",
     "legendFormat": "t < 800ms"
    },
    {
     "expr": "(sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"1200.0\", status=\"ok\"}) - sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"800.0\", status=\"ok\"})) or vector(0)",
     "legendFormat": "800ms ≤ t < 1200ms"
    },
    {
     "expr": "(sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"+Inf\", status=\"ok\"}) - sum(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", le=\"1200.0\", status=\"ok\"})) or vector(0)",
     "legendFormat": "t ≥ 1200ms"
    },
    {
     "expr": "sum(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ko\"}) or vector(0)",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (request) (gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\"})",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "sum by (request) (gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"})",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "sum by (request) (gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ko\"}) or (sum by (request) (gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\"}) * 0)",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "sum by (request) (increase(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\"}[$__range])) / $__range_s",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (request, le) (increase(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__range])))",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (request, le) (increase(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__range])))",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (request, le) (increase(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__range])))",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (request, le) (increase(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__range])))",
     "legendFormat": "{{request}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (request, le) (increase(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__range])))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Active Users Along the Simulation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Active Users along the Simulation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (scenario) (gatling_active_users{simulation=~\"$simulation\", scenario=~\"$scenario\"})",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Response Time Percentiles over Time (OK)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Response Time Percentiles over Time (OK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(gatling_active_users{simulation=~\"$simulation\", scenario=~\"$scenario\"})",
     "legendFormat": "Active Users"
    }
   ]
  },
  { "title": "Number of Requests per Second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Number of requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(gatling_active_users{simulation=~\"$simulation\", scenario=~\"$scenario\"})",
     "legendFormat": "Active Users"
    }
   ]
  },
  { "title": "Number of Responses per Second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Number of responses per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(gatling_requests_total{status=\"ok\"}[$__rate_interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ko\"}[$__rate_interval]))",
     "legendFormat": "KO"
    },
    {
     "expr": "sum(gatling_active_users{simulation=~\"$simulation\", scenario=~\"$scenario\"})",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Response Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_requests_total{status=\"ok\"})",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(gatling_requests_total{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ko\"}) or vector(0)",
     "legendFormat": "KO"
    }
   ]
  },
  { "title": "Details (Per Request)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Response Time P95 (Per Request)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (request, le) (rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Response Time Percentiles over Time (Per Request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (request, le) (rate(gatling_response_time_milliseconds_bucket{simulation=~\"$simulation\", scenario=~\"$scenario\", request=~\"$request\", status=\"ok\"}[$__rate_interval])))",
     "legendFormat": "{{request}} P95"
    }
   ]
  },
  {
   "title": "Number of Responses per Second (Per Request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (request) (rate(gatling_requests_total{status=\"ok\"}[$__rate_interval]))",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}