name: 🚀 Feature Request
description: 새로운 기능을 제안합니다.
labels: ["new feature"]
body:
  - type: textarea
    id: context
    attributes:
      label: 💡 제안 배경
      description: 왜 이 기능이 필요한가요?
      value: |
        ---
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 📋 기능 상세 내용
      description: 구체적인 동작 방식이나 요구사항을 작성해주세요.
      value: |
        ---
    validations:
      required: true
