plugins {
    id 'java'
    alias(libs.plugins.gatling)
    alias(libs.plugins.shadow)
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.java.get())
    }
}

// Gatling 플러그인이 test 출력물을 gatling classpath에 포함하는 것을 끄면
// compileGatlingJava → testClasses 의존을 피할 수 있다.
gatling {
    includeTestOutput = false
}

configurations {
    testImplementation.extendsFrom(configurations.gatlingImplementation)
}

dependencies {

    // prometheus
    gatlingImplementation libs.prometheus.metrics.core
    gatlingImplementation libs.prometheus.metrics.exposition.formats
    gatlingImplementation libs.prometheus.metrics.instrumentation.jvm
    gatlingImplementation libs.prometheus.metrics.exporter.httpserver

    // gatling output
    testImplementation sourceSets.gatling.output

    // JUnit
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly    libs.junit.platform.launcher

    // assertJ
    testImplementation libs.assertj.core

    // testcontainers
    testImplementation platform(libs.testcontainers.bom)
    testImplementation libs.testcontainers.core
    testImplementation libs.testcontainers.junit.jupiter

    // awaitility
    testImplementation libs.awaitility

    // slf4j
    testRuntimeOnly libs.slf4j.simple
}

compileTestJava.dependsOn(compileGatlingJava)

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('gatling-runner')
    archiveClassifier.set('')
    archiveVersion.set('1.0.0')

    manifest {
        attributes 'Main-Class': 'io.github.eottabom.gatling.runner.GatlingRunner'
    }

    from sourceSets.gatling.output

    configurations = [project.configurations.gatlingRuntimeClasspath]

    mergeServiceFiles()

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

shadowJar.dependsOn(compileGatlingJava)

build.dependsOn shadowJar