plugins {
    id 'java'
    id 'io.gatling.gradle'
    id 'com.gradleup.shadow'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

// Gatling 플러그인이 test 출력물을 gatling classpath에 포함하는 것을 끄면
// compileGatlingJava → testClasses 의존을 피할 수 있다.
gatling {
    includeTestOutput = false
}

configurations {
    testImplementation.extendsFrom(configurations.gatlingImplementation)
}

dependencies {

    // prometheus
    gatlingImplementation "io.prometheus:prometheus-metrics-core:${prometheusVersion}"
    gatlingImplementation "io.prometheus:prometheus-metrics-exposition-formats:${prometheusVersion}"
    gatlingImplementation "io.prometheus:prometheus-metrics-instrumentation-jvm:${prometheusVersion}"
    gatlingImplementation "io.prometheus:prometheus-metrics-exporter-httpserver:${prometheusVersion}"

    // gatling output
    testImplementation sourceSets.gatling.output

    // JUnit
    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly   "org.junit.platform:junit-platform-launcher"

    // assertJ
    testImplementation "org.assertj:assertj-core:${assertjVersion}"

    // testcontainers
    testImplementation platform("org.testcontainers:testcontainers-bom:${testcontainersVersion}")
    testImplementation "org.testcontainers:testcontainers"
    testImplementation "org.testcontainers:junit-jupiter"

    // awaitility
    testImplementation "org.awaitility:awaitility:${awaitilityVersion}"

    testRuntimeOnly "org.slf4j:slf4j-simple:${slf4jVersion}"
}

compileTestJava.dependsOn(compileGatlingJava)

test {
    useJUnitPlatform()
    environment "TESTCONTAINERS_RYUK_DISABLED", "true"
}

shadowJar {
    archiveBaseName.set('gatling-runner')
    archiveClassifier.set('')
    archiveVersion.set('1.0.0')

    manifest {
        attributes 'Main-Class': 'io.github.eottabom.gatling.runner.GatlingRunner'
    }

    from sourceSets.gatling.output

    configurations = [project.configurations.gatlingRuntimeClasspath]

    mergeServiceFiles()

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

shadowJar.dependsOn(compileGatlingJava)

build.dependsOn shadowJar
