plugins {
    id 'java'
    id 'io.gatling.gradle'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

dependencies {
    gatlingImplementation "io.prometheus:prometheus-metrics-core:${prometheusVersion}"
    gatlingImplementation "io.prometheus:prometheus-metrics-exposition-formats:${prometheusVersion}"
    gatlingImplementation "io.prometheus:prometheus-metrics-instrumentation-jvm:${prometheusVersion}"
    gatlingImplementation "io.prometheus:prometheus-metrics-exporter-httpserver:${prometheusVersion}"
}